export const PG_DATA_SOURCE = 'PG_DATA_SOURCE';

/**
 *
 * Repositories
 */
export const ORGANIZATION_REPOSITORY = 'ORGANIZATION_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TOKEN_REPOSITORY = 'TOKEN_REPOSITORY';
